(define (reset-top-binding)
          "Reset top-level binding"
        (ungrab-all-keys)
        (remove-all-keys)
        (top-binding)
        (grab-all-keys))

(define (new-browser)
          "New browser"
        (ungrab-all-keys)
        (remove-all-keys)
        (xbindkey-function "c" (lambda ()
                                       (run-command "chromium-browser")
                                       (reset-top-binding)))
        (xbindkey-function "f" (lambda ()
                                       (run-command "firefox")
                                       (reset-top-binding)))
        (xbindkey-function '(control g) (lambda ()
                                       (reset-top-binding)))
        (grab-all-keys))

(define (new-terminal)
          "New terminal"
        (ungrab-all-keys)
        (remove-all-keys)
        (xbindkey-function "1" (lambda ()
                                       (run-command "gnome-terminal")
                                       (reset-top-binding)))
        (xbindkey-function "2" (lambda ()
                                       (run-command "gnome-terminal --geometry=80x57")
                                       (reset-top-binding)))
        (xbindkey-function "3" (lambda ()
                                       (run-command "gnome-terminal --geometry=100x57")
                                       (reset-top-binding)))
        (xbindkey-function "4" (lambda ()
                                       (run-command "gnome-terminal --geometry=211x32")
                                       (reset-top-binding)))
        (xbindkey-function '(control g) (lambda ()
                                       (reset-top-binding)))
        (grab-all-keys))

(define (top-binding)
        (xbindkey-function '(control n) new-terminal)
        (xbindkey-function '(control b) new-browser))

(top-binding)
